export enum NotificationReasonTypesEnum {
    NOTIFICATION_NORMAL = 0,
    NOTIFICATION_ACKNOWLEDGEMENT = 1,
    NOTIFICATION_FLAPPINGSTART = 2,
    NOTIFICATION_FLAPPINGSTOP = 3,
    NOTIFICATION_FLAPPINGDISABLED = 4,
    NOTIFICATION_DOWNTIMESTART = 5,
    NOTIFICATION_DOWNTIMEEND = 6,
    NOTIFICATION_DOWNTIMECANCELLED = 7,
    NOTIFICATION_CUSTOM = 8
}
