import {
    AfterViewInit,
    ChangeDetectionStrategy,
    Component,
    ElementRef,
    inject,
    signal,
    ViewChild
} from '@angular/core';
import { BaseWidgetComponent } from '../../../../pages/dashboards/widgets/base-widget/base-widget.component';
import { KtdGridLayout, KtdResizeEnd } from '@katoid/angular-grid-layout';
import { GrafanaAutogeneratedWidgetService } from './grafana-autogenerated-widget.service';
import { SelectKeyValue } from '../../../../layouts/primeng/select.interface';
import { FormLabelDirective } from '@coreui/angular';
import { RequiredIconComponent } from '../../../../components/required-icon/required-icon.component';
import { SelectComponent } from '../../../../layouts/primeng/select/select/select.component';
import { FaIconComponent } from '@fortawesome/angular-fontawesome';

import { FormsModule } from '@angular/forms';
import { TranslocoDirective } from '@jsverse/transloco';
import { XsButtonDirective } from '../../../../layouts/coreui/xsbutton-directive/xsbutton.directive';
import { IframeComponent } from '../../../../components/iframe/iframe.component';
import { AnimationEvent } from '@angular/animations';

@Component({
    selector: 'oitc-grafana-autogenerated-widget',
    imports: [
    FormLabelDirective,
    RequiredIconComponent,
    SelectComponent,
    FaIconComponent,
    FormsModule,
    TranslocoDirective,
    XsButtonDirective,
    IframeComponent
],
    templateUrl: './grafana-autogenerated-widget.component.html',
    styleUrl: './grafana-autogenerated-widget.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class GrafanaAutogeneratedWidgetComponent extends BaseWidgetComponent implements AfterViewInit {
    protected flipped = signal<boolean>(false);
    @ViewChild('boxContainer') boxContainer?: ElementRef;
    public widgetHeight: number = 0;

    public host_id: null | number = null;
    public iframe_url: string = '';

    public grafanaDashboards: SelectKeyValue[] = [];

    private readonly GrafanaAutogeneratedWidgetService = inject(GrafanaAutogeneratedWidgetService);

    public override load() {
        if (this.widget) {
            this.GrafanaAutogeneratedWidgetService.loadWidgetConfig(this.widget.id).subscribe((response) => {
                this.host_id = response.host_id;
                this.iframe_url = response.iframe_url;
                this.cdr.markForCheck();
            });
        }
    }

    public ngAfterViewInit(): void {
        this.calcIframeHeight();
    }

    public override onAnimationStart(event: AnimationEvent) {
        if (event.toState && this.grafanaDashboards.length === 0) {
            // "true" means show config.
            // Load initial Grafana Dashboards
            this.loadGrafanaDashboards('');
        }

        super.onAnimationStart(event);
    }

    private calcIframeHeight() {
        this.widgetHeight = this.boxContainer?.nativeElement.offsetHeight;

        let height = this.widgetHeight - 29 - 12; //Unit: px
        //                                        ^ Show / Hide Config button
        //                                            ^ Some Padding

        if (height < 15) {
            height = 15;
        }

        this.widgetHeight = height;
        this.cdr.markForCheck();
    }

    public saveConfig() {
        if (this.host_id && this.widget) {
            this.GrafanaAutogeneratedWidgetService.saveWidgetConfig(this.widget.id, this.host_id).subscribe((response) => {
                // Update the markdown content
                this.load();

                // Close config
                this.flipped.set(false);
            });
        }
    }

    public loadGrafanaDashboards = (searchString: string) => {
        this.subscriptions.add(this.GrafanaAutogeneratedWidgetService.loadGrafanaDashboards(searchString)
            .subscribe((result) => {

                const dashboards: SelectKeyValue[] = [];
                result.grafana_dashboards.forEach((dashboard) => {
                    dashboards.push({
                        key: dashboard.GrafanaDashboard.host_id,
                        value: dashboard.Host.name
                    });
                });

                this.grafanaDashboards = dashboards;

                this.cdr.markForCheck();
            })
        );
    };

    public override ngOnDestroy() {
        super.ngOnDestroy();
    }

    public override resizeWidget(event?: KtdResizeEnd) {
        this.calcIframeHeight();
    }

    public override layoutUpdate(event: KtdGridLayout) {

    }
}
