export interface LoadGrafanaDashboardsRootResponse {
    grafana_dashboards: {
        GrafanaDashboard: {
            id: number
            host_id: number
            host_uuid: string
        }
        Host: {
            name: string
        }
    }[]
    _csrfToken: string | null
}

export interface GrafanaAutogeneratedWidgetConfigRootResponse {
    host_id: number
    iframe_url: string
    _csrfToken: string | null
}
