import { TestBed } from '@angular/core/testing';

import { GrafanaAutogeneratedWidgetService } from './grafana-autogenerated-widget.service';

describe('GrafanaAutogeneratedWidgetService', () => {
  let service: GrafanaAutogeneratedWidgetService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(GrafanaAutogeneratedWidgetService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
