export enum CumulatedStatuspagegroupStatus {
    CUMULATED_STATE_NOT_IN_MONITORING = -1,
    CUMULATED_STATE_OPERATIONAL = 0,
    CUMULATED_STATE_PERFORMANCE_ISSUES = 1,
    CUMULATED_STATE_MAJOR_OUTAGE = 2,
    CUMULATED_STATE_UNKNOWN = 3
}
